# Generated by Django 4.2.11 on 2024-12-15 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_category_alter_blog_posted_alter_comment_date_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 15, 18, 26, 47, 337489), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 15, 18, 26, 47, 337489), verbose_name='Дата комментария'),
        ),
    ]
